name: Nightly Build CI

on:
  push:
    branches:
      - master

jobs:
  build_and_publish:
    permissions:
      contents:
        write
    strategy:
      fail-fast: false
      matrix:
        settings:
          - platform: "macos-latest"
            args: "--target aarch64-apple-darwin"
          - platform: "macos-latest"
            args: "--target x86_64-apple-darwin"

    runs-on: ${{ matrix.settings.platform }}

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "npm install"
        run: npm ci

      - name: "install Rust"
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.settings.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      # - name: install dependencies (ubuntu only)
      #   if: matrix.settings.platform == 'ubuntu-22.04' # This must match the platform value defined above.
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Build
        run: npm run tauri build

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: mac-app
          path: ./src-tauri/target/release/bundle/macos/smash.app
